### ISSUE TITLE
front-server在用户信息查询和用户信息更新时存在bug

### ISSUE THREAD

**Issue by lpxofbuaa** [BUAASoftwareEngineering/vLab-Backend#15]
- 查询用户信息时，报“用户找不到”错误
- 更新用户信息时，报“用户找不到”错误
- cookie的路径应该设置为根目录
- user_info和user_update_info的返回信息不要有password字段

**Comment by Knowden** [comment]
bug与非功能bug修复完成，已与前端完成对接
